paths:
  dbc: "A5.dbc"
  seed_db: "seeds.db"
  logs: "logs/"

can:
  enable: true
  channel: "can0"      
  default_id: "0x6A6"
  force_default_id: true

fuzz:
  timing_timeout: 5.0
  dbc_timeout: 5.0