nrc_fail_list:
  - "0x11"  # ServiceNotSupported
  - "0x12"  # SubFunctionNotSupported
  - "0x13"  # IncorrectMessageLengthOrInvalidFormat
  - "0x14"  # ResponseTooLong
  - "0x24"  # RequestSequenceError
  - "0x31"  # RequestOutOfRange
  - "0x70"  # UploadDownloadNotAccepted
  - "0x72"  # GeneralProgrammingFailure